# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f4a46eb85235b85e6beee9c5a9196e8b36b8a20b2f61083e73bf6d959acf680d49b2854366ed167c2d8bff163c0ef21b9c2479e0a882fea95cdb617e5b103a7

test:
  secret_key_base: 6f33c151a6cb543c4699e41a2ac4f3e80d08f3ef7b437e1be7fb0eb8af43c20097cbb080a9c7cb4f291bb5efb0a497a60a4fd9df3340dc5d1441f1bc683646ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
